development:
  adapter: postgresql
  encoding: unicode
  database: unlisted_development
  pool: 5
  username: zack
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: unlisted_test
  pool: 5
  username: zack
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: unlisted_production
  pool: 5
  username: zack
  password:
  host: localhost
